### ISSUE TITLE
Problem with resolving dependencies that require a specific minimum version

### ISSUE THREAD

**Issue by hctom** [drupal-composer/drupal-parse-composer#22]
I am currently working on a project to install Drupal and some contrib modules via Composer. Everything works fine, but when a module (in my case ```flexslider```) requires a minimum version of another module, the minimum version is determined wrong somehow.

Here is my ```composer.json``` file:

```
{
  "name": "project",
  "description": "Project",
  "authors": [],
  "repositories": [
    {
      "type": "composer",
      "url": "http://drupal-packagist.webflo.io/"
    }
  ],
  "minimum-stability": "dev",
  "prefer-stable": true,
  "require": {
    "drupal/drupal": "7.*",
    "drupal/libraries": "7.2.2",
    "drupal/flexslider": ">7.2.0-alpha3"
  }
}
```

According to the ```.info```file of the ```flexslider``` module, it requires the ```(>=2.x)``` version of the ```libraries```module:

```
; Dependencies
dependencies[] = libraries (>=2.x)
```

Unfortunately this does not fulfill my ```composer.json```requirements with version ```7.2.2```, even though this should be a valid version number for the ```libraries``` module because it is ```>=2.x```.

I'd appreciate, if you can have a look at this, so I don't need to use the ```7.2.x-dev```version of the ```libraries```module, but the stable release that should fulfill all requirements.

Thanx in advance & cheers

hctom

**Comment by winmillwill** [comment]
This is just an issue with stale metadata. This bug has been fixed in this library and the metadata needs to be updated with the current code.

**Comment by webflo** [comment]
@winmillwill Nope, this was another issue. Fixed in https://github.com/drupal-composer/drupal-parse-composer/commit/4408da5405e1fde74f2367fbb5d7a0293f51c767

Added a test case to phpspec.

**Comment by hctom** [comment]
Yeah! Thanx a lot! Will give this a try tomorrow
