### ISSUE TITLE
README

### ISSUE THREAD

**Issue by davidbarratt** [drupal-composer/drupal-parse-composer#5]
[generalredneck](https://www.drupal.org/u/generalredneck) provided some good [instructions](https://www.drupal.org/node/1886820#comment-9043671) on how to use this library / service.

I was wondering if you could write a README on the best way to use this library? (i.e. what urls to use and also how to clone / install on our own server).

Thanks!

**Comment by webflo** [comment]
I think we could close this issue a point people directly to https://github.com/drupal-composer/drupal-packagist because this repo contains everything you need.
