### ISSUE TITLE
drupal/migrate_plus depends on drupal/system 8.8.1

### ISSUE THREAD

**Issue by hussainweb** [drupal-composer/drupal-parse-composer#51]
The module [migrate_plus](https://packagist.drupal-composer.org/packages/drupal/migrate_plus#8.1.0) lists a dependency on system (>8.1). This translates in the composer.json file on drupal-packagist to `>8.8.1`, which is not valid. I have created a pull request #50 that should hopefully fix this problem.

**Comment by hussainweb** [comment]
Thanks! How soon will this change take effect?

**Comment by webflo** [comment]
Did a forced update on drupal/migrate_plus, drupal/migrate_upgrade and drupal/migrate_tools a few seconds ago. Everything should work now. You may have to run composer clear-cache.

**Comment by hussainweb** [comment]
Thanks! It works now. I didn't even need to `composer clear-cache`.
