### ISSUE TITLE
undiscovered d.o module: teacosy

### ISSUE THREAD

**Issue by joshbotnet** [drupal-composer/drupal-parse-composer#55]
d.o module: https://www.drupal.org/project/teacosy
packagist: https://packagist.drupal-composer.org/search/?q=teacosy

My other modules were discovered fine, just this one is missing.
Is there a way to prompt drupal packagist to discover it?

thanks
Josh

**Comment by joshbotnet** [comment]
nvm - it's arrived now

**Comment by webflo** [comment]
Great :)
