### ISSUE TITLE
composer.json versions are getting ~ added to them.

### ISSUE THREAD

**Issue by generalredneck** [drupal-composer/drupal-parse-composer#56]
In the case of drupal/search_api_solr 8.1.0-alpha4, this is what the [packagist](https://packagist.drupal-composer.org/p/drupal/search_api_solr.json) is saying the dependencies are:

```json
"require": {
"solarium/solarium": "~3.5.1",
"drupal/core": "8.*",
"drupal/search_api": "8.*"
}
```

The [composer.json](http://cgit.drupalcode.org/search_api_solr/tree/composer.json?h=8.x-1.0-alpha4) file that is shipped with the module says:

```json
    "require": {
        "solarium/solarium": "3.5.1"
    }
```

Why is the ~ being added to solarioum/solarium

**Comment by phenaproxima** [comment]
This exact complaint was filed against Drupal Packagist: drupal-composer/drupal-packagist#63

**Comment by phenaproxima** [comment]
Discussed with @webflo, who pinpointed the problem to d7a00788d3dcfd3ce0b2aac55abdb64c47246840.

**Comment by webflo** [comment]
Fixed the bug and triggered a forced update on search_api_solr https://packagist.drupal-composer.org/packages/drupal/search_api_solr#8.1.0-alpha4
